name: openfold-venv
channels:
  - conda-forge
  - bioconda
  - pytorch
  - nvidia 
dependencies:
  - python=3.9
  - libgcc=7.2
  - setuptools=59.5.0
  - pip
  - openmm=7.7
  - pdbfixer
  - pytorch-lightning
  - biopython==1.79
  - numpy
  - pandas
  - PyYAML==5.4.1
  - requests
  - scipy
  - tqdm==4.62.2
  - typing-extensions
  - wandb
  - modelcif==0.7
  - awscli
  - ml-collections
  - aria2
  - git
  - bioconda::hmmer==3.3.2
  - bioconda::hhsuite==3.3.0
  - bioconda::kalign2==2.04
  - pytorch::pytorch=2.1
  - pytorch::pytorch-cuda=12.1
  - pip:
      - deepspeed==0.12.4
      - dm-tree==0.1.6
      - git+https://github.com/NVIDIA/dllogger.git
      - flash-attn 
